//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbot.WaterbotServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waterbot.WaterbotServer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl+C to stop Waterbot.
        /// </summary>
        internal static string Con_ExitMessage {
            get {
                return ResourceManager.GetString("Con_ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterbot server.
        /// </summary>
        internal static string Con_Title {
            get {
                return ResourceManager.GetString("Con_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load {0}. Please check whether the file is accessible and valid and try again..
        /// </summary>
        internal static string ConfigLoadFailed {
            get {
                return ResourceManager.GetString("ConfigLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default configuration has been written to {0}. Please check the file, modify it where necessary, then start Waterbot again..
        /// </summary>
        internal static string DefaultConfigCreated {
            get {
                return ResourceManager.GetString("DefaultConfigCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the Waterbot server..
        /// </summary>
        internal static string Help_Description {
            get {
                return ResourceManager.GetString("Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterbotServer [--config=VALUE] [channel].
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of the configuration to load..
        /// </summary>
        internal static string Opt_Config {
            get {
                return ResourceManager.GetString("Opt_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints this message and exits..
        /// </summary>
        internal static string Opt_Help {
            get {
                return ResourceManager.GetString("Opt_Help", resourceCulture);
            }
        }
    }
}
