//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbot.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waterbot.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about now.
        /// </summary>
        internal static string AboutNow {
            get {
                return ResourceManager.GetString("AboutNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0:N0} days.
        /// </summary>
        internal static string AboutXDays {
            get {
                return ResourceManager.GetString("AboutXDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0:N0} hours.
        /// </summary>
        internal static string AboutXHours {
            get {
                return ResourceManager.GetString("AboutXHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0:N0} minutes.
        /// </summary>
        internal static string AboutXMinutes {
            get {
                return ResourceManager.GetString("AboutXMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about {0:N0} seconds.
        /// </summary>
        internal static string AboutXSeconds {
            get {
                return ResourceManager.GetString("AboutXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and an hour.
        /// </summary>
        internal static string AndOneHour {
            get {
                return ResourceManager.GetString("AndOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and one minute.
        /// </summary>
        internal static string AndOneMinute {
            get {
                return ResourceManager.GetString("AndOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and one second.
        /// </summary>
        internal static string AndOneSecond {
            get {
                return ResourceManager.GetString("AndOneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0:N0} hours.
        /// </summary>
        internal static string AndXHours {
            get {
                return ResourceManager.GetString("AndXHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0:N0} minutes.
        /// </summary>
        internal static string AndXMinutes {
            get {
                return ResourceManager.GetString("AndXMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and {0:N0} seconds.
        /// </summary>
        internal static string AndXSeconds {
            get {
                return ResourceManager.GetString("AndXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a couple of seconds.
        /// </summary>
        internal static string FewSecs {
            get {
                return ResourceManager.GetString("FewSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0}.
        /// </summary>
        internal static string InX {
            get {
                return ResourceManager.GetString("InX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string XAgo {
            get {
                return ResourceManager.GetString("XAgo", resourceCulture);
            }
        }
    }
}
