//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waterbot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waterbot.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No behavior specified for {0}, falling back to default behavior.
        /// </summary>
        internal static string BehaviorFallback {
            get {
                return ResourceManager.GetString("BehaviorFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration is required to call this method..
        /// </summary>
        internal static string ConfigRequired {
            get {
                return ResourceManager.GetString("ConfigRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from Twitch!.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And we&apos;re back!.
        /// </summary>
        internal static string ConnectionRestored {
            get {
                return ResourceManager.GetString("ConnectionRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying in {0}....
        /// </summary>
        internal static string ConnectionRetrying {
            get {
                return ResourceManager.GetString("ConnectionRetrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        internal static string InvalidOperation_Null {
            get {
                return ResourceManager.GetString("InvalidOperation_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} disabled Mute in channel {1}.
        /// </summary>
        internal static string MuteDisabled {
            get {
                return ResourceManager.GetString("MuteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} enabled Mute in channel {1}.
        /// </summary>
        internal static string MuteEnabled {
            get {
                return ResourceManager.GetString("MuteEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I&apos;m talking to myself..
        /// </summary>
        internal static string TalkingToMyself {
            get {
                return ResourceManager.GetString("TalkingToMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started streaming {1}..
        /// </summary>
        internal static string UptimeResponse {
            get {
                return ResourceManager.GetString("UptimeResponse", resourceCulture);
            }
        }
    }
}
